modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/olympus/issues"

[[mods]]
modId = "olympus"
version = "${version}"
displayName = "Olympus"
displayURL = "https://github.com/terrarium-earth/olympus"
logoFile = "icon.png"
authors = "ThatGravyBoat"
description = "Common Components library for Project Odyssey."

[[mixins]]
config = "olympus.mixins.json"
[[mixins]]
config = "olympus-common.mixins.json"

[[dependencies.olympus]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.olympus]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.olympus]]
modId = "resourcefullib"
type="required"
versionRange = "[2.4.8,)"
ordering = "NONE"
side = "BOTH"
