modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/olympus/issues"

[[mods]]
modId = "olympus"
version = "${version}"
displayName = "Olympus"
displayURL = "https://github.com/terrarium-earth/olympus"
logoFile = "icon.png"
authors = "ThatGravyBoat"
description = "Common Components library for Project Odyssey."

[[dependencies.olympus]]
modId = "neoforge"
type="required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.olympus]]
modId = "minecraft"
type="required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.olympus]]
modId = "resourcefullib"
type="required"
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "BOTH"
